version: '3'
services:

  postgres:
    image: 'postgres:13'
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - '$HOME/postgresql/etl_data:/var/lib/postgresql/etl_data'
    ports:
      - '5432:5432'  

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.6.2'  
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms1000m -Xmx1000m'
      - xpack.security.enabled=false  
    ports:
      - '9200:9200'

  etl:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - elasticsearch    